### ISSUE TITLE
Cannot get CloudSlang Hello World example to execute

### ISSUE THREAD

**Issue by gitsaf** [natabeck/slang-webapp#2]
I've imported the repository into Eclipse as a project. I run Maven from within Eclipse, and the web application starts up fine.

I am successful running the example provided in README.md. For that example, I put my print.sl into a C:\MyFlows directory on my dev system. 

Here is the JSON I send as the request body

{"slangFilePath":"C:\MyFlows\print.sl","slangDir":"C:\MyFlows","runInputs":{"text":"Well, Hello"}}

I see this successfully execute on the server side in Eclipse, and get a successful response in my REST Client.

I have not had success running the Hello World flow example, which simply wraps this print operation.

In that scenario I add the hello_world.sl file to C:\MyFlows and change the JSON request to:
{"slangFilePath":"C:\MyFlows\hello_world.sl","slangDir":"C:\MyFlows"}

This configuration fails with apparently an inability to find the print operation

2016-05-16 13:28:06.791 ERROR 2420 --- [nio-9222-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: Error transforming source: hello_world.sl to a Slang model. No imports specified for source: print] with root cause

java.lang.IllegalArgumentException: No imports specified for source: print
    at org.apache.commons.lang.Validate.notNull(Validate.java:192)
    at io.cloudslang.lang.compiler.modeller.ExecutableBuilder.resolveRefId(ExecutableBuilder.java:271)

If I change the print operation to live in another namespace (e.g. examples.print instead of examples.hello_world) and then import that namespace into the hello_world.sl file, I no longer get the import error. Additionally, the REST call returns successfully. However, I see the following error in the server console and the print does not work.

2016-05-16 14:23:50.050  INFO 14200 --- [ead-0_100000001] o.h.e.j.b.internal.AbstractBatchImpl     : HHH000010: On release of batch it still contained JDBC statements
2016-05-16 14:23:50.051  WARN 14200 --- [ead-0_100000001] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 22001, SQLState: 22001
2016-05-16 14:23:50.051 ERROR 14200 --- [ead-0_100000001] o.h.engine.jdbc.spi.SqlExceptionHelper   : Value too long for column "RESULT VARCHAR(255)": "STRINGDECODE('Error running: sayHi: Error binding input: ''text'', error is: \nError in running script expression or variable re... (271)"; SQL statement:
update EXECUTION_SUMMARY set EXECUTION_ID=?, OUTPUTS=?, RESULT=?, STATUS=? where ID=? [22001-183]
2016-05-16 14:23:50.051  WARN 14200 --- [ead-0_100000001] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 22001, SQLState: 22001
2016-05-16 14:23:50.051 ERROR 14200 --- [ead-0_100000001] o.h.engine.jdbc.spi.SqlExceptionHelper   : Value too long for column "RESULT VARCHAR(255)": "STRINGDECODE('Error running: sayHi: Error binding input: ''text'', error is: \nError in running script expression or variable re... (271)"; SQL statement:
update EXECUTION_SUMMARY set EXECUTION_ID=?, OUTPUTS=?, RESULT=?, STATUS=? where ID=? [22001-183]
2016-05-16 14:23:50.052 ERROR 14200 --- [ead-0_100000001] o.h.e.jdbc.batch.internal.BatchingBatch  : HHH000315: Exception executing batch [could not execute batch]

Thoughts?

**Comment by gitsaf** [comment]
I'm hoping someone can take a look at this issue soon. Perhaps I am just not specifying SlangDir correctly given it is running from within my Eclipse environment?

**Comment by gitsaf** [comment]
The last error is related to the Results column not being large enough to handle the message being returned by CloudSlang. I fixed this by making Results varchar(max).

Now I can see the error that is really happening when I get the execution result:

"Error running: sayHi: Error binding input: 'msg', error is: \nError in running script expression or variable reference, for expression: 'Hello From the Flow', Script exception is: \njavax.script.ScriptException: SyntaxError: no viable alternative at input 'From' in <script> at line number 1 at column number 6",

Please help. This is a very simple Hello World with a flow sending "Hello From the Flow" as the input to the print function.

**Comment by gitsaf** [comment]
Misuse of Closed
